[build]
  command = "npm run build"
  publish = "build"
  base ="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  GENERATE_SOURCEMAP = "true"

[build.production.environment]
  GENERATE_SOURCEMAP = "false"